trigger:
  batch: true
  branches:
    include: [ main ]

pr: none

stages:
- stage: Deploy
  jobs:

  - deployment: Shared
    environment: shared-ia
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - template: templates/deploy-template.yml