trigger: none

parameters:
  - name: environment
    displayName: 'Demo Environment'
    type: string
    default: 'demo-red'
    values:
      - demo-red
      - demo-blue

pr: none

if: ${{ eq(parameters.environment, 'demo-red') }} || ${{ eq(parameters.environment, 'demo-blue') }}

stages:
- stage: DeployDemoRed
  displayName: 'Deploy to Demo Red'
  condition: eq(parameters.environment, 'demo-red')

  jobs:

  - deployment: 'DeployRed'
    environment: demo-red
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - template: templates/deploy-template.yml

- stage: DeployDemoBlue
  displayName: 'Deploy to $(environment)'
  condition: eq(parameters.environment, 'demo-blue')
  jobs:

  - deployment: 'DemoBlue'
    environment: demo-blue
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - template: templates/deploy-template.yml