# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

trigger:
  batch: true
  branches:
    include: [ vNext-Dev ]

pr: none

stages:
- stage: Deploy
  jobs:

  - deployment: Shared
    environment: $(environment)
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - template: templates/deploy-template.yml