# Use the official Python image from Microsoft for Azure App Service
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

COPY app/enrichment /app

# Expose the port the app runs on
EXPOSE 8000